import { ChildTaskConfig } from "./model";

export const config: ChildTaskConfig[] = [
  {
    name: "Jacob",
    startTime: "07:45",
    tasks: [
      { name: "Eat breakfast", emoji: "🥣", duration: 30 },
      { name: "Brush teeth", emoji: "🪥", duration: 3 },
      { name: "Wash face", emoji: "🧼", duration: 2 },
      { name: "Get dressed", emoji: "👕", duration: 15 },
      { name: "Choose snack", emoji: "🍎", duration: 2 },
      { name: "Fill water bottle", emoji: "💧", duration: 2 },
      { name: "Brush hair", emoji: "🪮", duration: 2 },
      { name: "Shoes on", emoji: "👟", duration: 1 },
      { name: "Coat on", emoji: "🧥", duration: 1 },
    ],
    colorClass: "bg-red-600",
    activities: { tuesday: ["pe"], thursday: ["pe"], wednesday: ["outdoor"] },
  },
  {
    name: "Calum",
    startTime: "07:45",
    tasks: [
      { name: "Eat breakfast", emoji: "🥣", duration: 30 },
      { name: "Brush teeth", emoji: "🪥", duration: 3 },
      { name: "Wash face", emoji: "🧼", duration: 2 },
      { name: "Get dressed", emoji: "👕", duration: 15 },
      { name: "Choose snack", emoji: "🍎", duration: 2 },
      { name: "Fill water bottle", emoji: "💧", duration: 2 },
      { name: "Brush hair", emoji: "🪮", duration: 2 },
      { name: "Shoes on", emoji: "👟", duration: 1 },
      { name: "Coat on", emoji: "🧥", duration: 1 },
    ],
    colorClass: "bg-blue-600",
    activities: { wednesday: ["pe"], thursday: ["pe"], monday: ["outdoor"] },
  },
  {
    name: "Dylan",
    startTime: "07:45",
    tasks: [
      { name: "Eat breakfast", emoji: "🥣", duration: 30 },
      { name: "Brush teeth", emoji: "🪥", duration: 3 },
      { name: "Wash face", emoji: "🧼", duration: 2 },
      { name: "Get dressed", emoji: "👕", duration: 15 },
      { name: "Choose snack", emoji: "🍎", duration: 2 },
      { name: "Fill water bottle", emoji: "💧", duration: 2 },
      { name: "Brush hair", emoji: "🪮", duration: 2 },
      { name: "Shoes on", emoji: "👟", duration: 1 },
      { name: "Coat on", emoji: "🧥", duration: 1 },
    ],
    colorClass: "bg-purple-300",
    activities: { monday: ["pe"], friday: ["pe"], wednesday: ["outdoor"] },
  },
];
