import { ChildTaskConfig } from "./model";

export const config: ChildTaskConfig[] = [
  {
    name: "Jacob",
    startTime: "07:45",
    tasks: [
      { id: "eat-breakfast", name: "Eat breakfast", emoji: "🥣", duration: 30 },
      { id: "brush-teeth", name: "Brush teeth", emoji: "🪥", duration: 3 },
      { id: "wash-face", name: "Wash face", emoji: "🧼", duration: 2 },
      { id: "get-dressed", name: "Get dressed", emoji: "👕", duration: 15 },
      { id: "choose-snack", name: "Choose snack", emoji: "🍎", duration: 2 },
      { id: "fill-bottle", name: "Fill bottle", emoji: "💧", duration: 2 },
      { id: "brush-hair", name: "Brush hair", emoji: "🪮", duration: 2 },
      { id: "shoes-on", name: "Shoes on", emoji: "👟", duration: 1 },
      { id: "coat-on", name: "Coat on", emoji: "🧥", duration: 1 },
    ],
    colorClass: "bg-red-600",
    activities: { tuesday: ["pe"], thursday: ["pe"], wednesday: ["outdoor"] },
  },
  {
    name: "Calum",
    startTime: "07:45",
    tasks: [
      { id: "eat-breakfast", name: "Eat breakfast", emoji: "🥣", duration: 30 },
      { id: "brush-teeth", name: "Brush teeth", emoji: "🪥", duration: 3 },
      { id: "wash-face", name: "Wash face", emoji: "🧼", duration: 2 },
      { id: "get-dressed", name: "Get dressed", emoji: "👕", duration: 15 },
      { id: "choose-snack", name: "Choose snack", emoji: "🍎", duration: 2 },
      { id: "fill-bottle", name: "Fill bottle", emoji: "💧", duration: 2 },
      { id: "brush-hair", name: "Brush hair", emoji: "🪮", duration: 2 },
      { id: "shoes-on", name: "Shoes on", emoji: "👟", duration: 1 },
      { id: "coat-on", name: "Coat on", emoji: "🧥", duration: 1 },
    ],
    colorClass: "bg-blue-600",
    activities: { wednesday: ["pe"], thursday: ["pe"], monday: ["outdoor"] },
  },
  {
    name: "Dylan",
    startTime: "07:45",
    tasks: [
      { id: "eat-breakfast", name: "Eat breakfast", emoji: "🥣", duration: 30 },
      { id: "brush-teeth", name: "Brush teeth", emoji: "🪥", duration: 3 },
      { id: "wash-face", name: "Wash face", emoji: "🧼", duration: 2 },
      { id: "get-dressed", name: "Get dressed", emoji: "👕", duration: 15 },
      { id: "choose-snack", name: "Choose snack", emoji: "🍎", duration: 2 },
      { id: "fill-bottle", name: "Fill bottle", emoji: "💧", duration: 2 },
      { id: "brush-hair", name: "Brush hair", emoji: "🪮", duration: 2 },
      { id: "shoes-on", name: "Shoes on", emoji: "👟", duration: 1 },
      { id: "coat-on", name: "Coat on", emoji: "🧥", duration: 1 },
    ],
    colorClass: "bg-purple-300",
    activities: { monday: ["pe"], friday: ["pe"], wednesday: ["outdoor"] },
  },
];
